Repository Cyber4All/learning-object-service, pull requests merged in 2019-03, with the labels that each got.

#264 Allow `page` and `currPage` as valid page param for backward compatibility
  package-lock.json
  package.json
  src/drivers/express/ExpressRouteDriver.ts
Labels: review

#265 Fix request timeout when token is invalid
  package-lock.json
  package.json
  src/drivers/express/ExpressDriver.ts
Labels: review

#268 Fix invalid access on public routes
  package-lock.json
  package.json
  src/drivers/express/ExpressDriver.ts
  src/middleware/authenticated-access.ts
  src/middleware/index.ts
  src/middleware/process-token.ts
Labels: review

#267 Feature/collection stats
  package-lock.json
  package.json
  src/Collections/CollectionInteractor.spec.ts
  src/Collections/RouteHandler.ts
  src/LearningObjectStats/LearningObjectStatStore.ts
  src/LearningObjectStats/LearningObjectStatsInteractor.ts
  src/drivers/MongoDriver.ts
Labels: review

#270 Add method to return child objects in correct order
  package-lock.json
  package.json
  src/LearningObjects/LearningObjectInteractor.ts
  src/drivers/MongoDriver.ts
  src/interfaces/DataStore.ts
  src/tests/mock-drivers/MockDataStore.ts
Labels: review

#276 Fix children array being copied to released-objects as an empty array
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#278 Remove outbound mapping of id to partial Learning Object
  package-lock.json
  package.json
  src/LearningObjects/LearningObjectInteractor.ts
  src/drivers/MongoDriver.ts
Labels: review

#272 Add routes to allow uploading to specific user
  package-lock.json
  package.json
  src/FileManager/FileInteractor.ts
  src/drivers/express/ExpressAuthRouteDriver.ts
Labels: review

#269 Refactor interactor level error handling into a function
  package-lock.json
  package.json
  src/interactors/LearningObjectInteractor.ts
Labels: review

#284 Patch PDFKit
  package-lock.json
  package.json
Labels: bug, review, security vulnerability

#260 add authorization to functions that modify learning object children
  package-lock.json
  package.json
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/interactors/LearningObjectInteractor.ts
Labels: review

#292 2.14.3
  package-lock.json
  package.json
Labels: review

#283 Upgrade to Gulp 4
  gulpfile.js
  package-lock.json
  package.json
Labels: review

#289 Remove package bloat
  package-lock.json
  package.json
  src/Collections/CollectionInteractor.spec.ts
  src/interactors/LearningObject.interactor.spec.ts
  tsconfig.json
Labels: review

#294 Fix NPM Audit Issues
  package-lock.json
  package.json
Labels: review

#296 Fix Internal Server Error on Child Modification
  package-lock.json
  package.json
  src/interactors/LearningObjectInteractor.ts
Labels: review

#291 Add the optional hasRevision flag to learning objects
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/entity/learning-object/learning-object.ts
  src/interactors/LearningObjectInteractor.ts
  src/types/learning-object-document.ts
Labels: review

#282 Fix Permission Issues on Parent Learning Objects
  gulpfile.js
  package-lock.json
  package.json
  src/LearningObjects/Hierarchy/HierarchyInteractor.ts
  src/LearningObjects/Hierarchy/HierarchyRouteHandler.ts
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressRouteDriver.ts
  src/interactors/LearningObjectInteractor.ts
  src/interfaces/DataStore.ts
Labels: review

#299 Fix cannot filter search by Standard Outcomes
  package-lock.json
  package.json
  src/drivers/express/ExpressRouteDriver.ts
Labels: bug, review
