Repository Cyber4All/learning-object-service, pull requests merged in 2019-06, with the labels that each got.

#320 Add an aggregation step to order files by date
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: priority: 3, review

#340 Refactor Unit Test Stubs
  package-lock.json
  package.json
  src/Changelogs/ChangelogDatastore.spec.ts
  src/Changelogs/ChangelogInteractor.spec.ts
  src/Collections/CollectionInteractor.spec.ts
  src/LearningObjectSubmission/interactors/cancelSubmission.spec.ts
  src/LearningObjects/LearningObjectInteractor.spec.ts
  src/LearningObjects/LearningObjectRouteHandler.spec.ts
  src/LearningOutcomes/LearningOutcomeRouteHandler.spec.ts
  src/app.ts
  src/drivers/MongoDriver.spec.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/shared/elasticsearch/HelperFunctions.spec.ts
  src/tests/mock-drivers/MockDataStore.ts
  src/tests/mock-drivers/MockLibraryDriver.ts
  src/tests/mock-drivers/MockS3Driver.ts
  src/tests/mocks.ts
  src/tests/stubs.ts
  test_environment/data.js
  test_environment/sharedIds.js
Labels: review

#338 Add Lambda Function Invocation For Sending Release Email
  Dockerfile
  package-lock.json
  package.json
  src/LearningObjects/Publishing/index.ts
  src/LearningObjects/Publishing/interactor.ts
  src/LearningObjects/Publishing/lambda-gateway-factory.ts
  src/LearningObjects/Publishing/lambda-gateway-stub.ts
  src/LearningObjects/Publishing/lambda-gateway.ts
  src/LearningObjects/Publishing/release-email-gateway.ts
Labels: review

#308 Reconfigure npm start scripts to use nodemon and tsc
  .gitignore
  .vscode/launch.json
  README.md
  nodemon.json
  package-lock.json
  package.json
  src/Changelogs/ChangelogDatastore.ts
  src/Changelogs/ChangelogInteractor.ts
  src/LearningObjectSubmission/interactors/checkFirstSubmission.ts
  src/LearningObjectSubmission/interactors/submitForReview.ts
  src/drivers/express/ExpressDriver.ts
  src/tests/mock-drivers/MockDataStore.ts
Labels: review

#348 Route admin and test traffic to LearningObjectSearch module
  .circleci/config.yml
  .gitignore
  elasticsearch_testing/.dockerignore
  elasticsearch_testing/Dockerfile
  elasticsearch_testing/babel.config.js
  elasticsearch_testing/elasticsearch-data/elasticsearch-responses.js
  elasticsearch_testing/elasticsearch-data/elasticsearch_learning-object_mapping.js
  elasticsearch_testing/elasticsearch-data/elasticsearch_seed.js
  elasticsearch_testing/gateways/elasticsearch_gateway.js
  elasticsearch_testing/gateways/learning-object-service-gateway.js
  elasticsearch_testing/gateways/learning-object-service-gateway.spec.js
  elasticsearch_testing/jest.config.js
  elasticsearch_testing/jest.setup.js
  elasticsearch_testing/package-lock.json
  elasticsearch_testing/package.json
  package-lock.json
  package.json
  src/LearningObjectSearch/adapters/ExpressHttpAdapter.ts
  src/drivers/express/ExpressDriver.ts
Labels: review

#379 Fix cancelSubmission bug
  package-lock.json
  package.json
  src/LearningObjectSubmission/interactors/cancelSubmission.ts
Labels: bug, review

#376 Add Release Authoring to CI
  .circleci/config.yml
  package-lock.json
  package.json
Labels: review

#383 Pull service version from package.json on Sentry release
  .circleci/config.yml
  package-lock.json
  package.json
Labels: review

#385 Temporarily disable Learning Object release email notifications
  package-lock.json
  package.json
  src/LearningObjects/Publishing/ReleaseEmails/lambda-gateway-factory.ts
Labels: review

#386 Revert "Temporarily disable Learning Object release email notifications"
  package-lock.json
  package.json
  src/LearningObjects/Publishing/ReleaseEmails/lambda-gateway-factory.ts
Labels: review

#387 Create feature toggle for release notifications
  package-lock.json
  package.json
  src/LearningObjects/Publishing/ReleaseEmails/lambda-gateway-factory.ts
Labels: review
