Repository Cyber4All/learning-object-service, pull requests merged in 2019-02, with the labels that each got.

#158 Implement integration tests for the LearningOutcome module
  package-lock.json
  package.json
  src/LearningObjectSubmission/SubmissionInteractor.spec.ts
  src/LearningOutcomes/LearningOutcomeRouteHandler.spec.ts
  src/LearningOutcomes/LearningOutcomeRouteHandler.ts
Labels: review

#202 Add handler for jwt middleware errors
  package-lock.json
  package.json
  src/drivers/express/ExpressDriver.ts
Labels: review

#181 Recursively update parent object's timestamps when child object is modified
  .gitignore
  Dockerfile
  jest.config.js
  package-lock.json
  package.json
  src/LearningObjectStats/LearningObjectStatStore.ts
  src/LearningObjects/LearningObjectInteractor.spec.ts
  src/LearningObjects/LearningObjectInteractor.ts
  src/LearningObjects/PDFKitDriver.ts
  src/drivers/MongoDriver.spec.ts
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/interactors/AuthorizationManager.spec.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/interactors/LearningObjectInteractor.ts
  src/interfaces/DataStore.ts
  src/tests/mock-drivers/MockDataStore.ts
  src/tests/mocks.ts
  src/types/user-token.ts
  test_environment/environment.js
  test_environment/globalConfig.json
  test_environment/seed.js
  test_environment/setup.js
  test_environment/teardown.js
  tsconfig.json
Labels: in progress, review

#203 Modify admin route to be able to query by collection
  package-lock.json
  package.json
  src/drivers/express/ExpressAdminRouteDriver.ts
  src/interactors/AdminLearningObjectInteractor.ts
Labels: review

#204 Use build method to get Datastore
  package-lock.json
  package.json
  src/app.ts
Labels: review

#207 Update buildSearchQuery function to use the status flag instead of the download lock when determining released status
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#206 Update aggregation to count released objects by status
  package-lock.json
  package.json
  src/LearningObjectStats/LearningObjectStatStore.ts
  src/drivers/MongoDriver.ts
Labels: review

#197 Fix LearningObject with children having incorrect date
  package-lock.json
  package.json
  src/interactors/LearningObjectInteractor.ts
  src/tests/mock-drivers/MockDataStore.ts
Labels: review

#211 :bug: Fix bug where requests to /learning-objects with one status filter fail
  package-lock.json
  package.json
  src/drivers/express/ExpressRouteDriver.ts
Labels: review

#215 Fix bug where /learning-objects route would create an array of null object(s) when no status filter applied.
  package-lock.json
  package.json
  src/drivers/express/ExpressRouteDriver.ts
Labels: review

#217 Include contributors in learning object summaries
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: WIP, review

#199 Remove use of the download lock and publish flag from the system
  package-lock.json
  package.json
  src/Changelogs/ChangelogDatastore.ts
  src/LearningObjectSubmission/SubmissionInteractor.ts
  src/LearningObjects/LearningObjectInteractor.ts
  src/drivers/MongoDriver.spec.ts
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressAdminRouteDriver.ts
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/drivers/express/ExpressDriver.ts
  src/drivers/express/ExpressRouteDriver.ts
  src/functions/index.ts
  src/interactors/AdminLearningObjectInteractor.ts
  src/interactors/AuthorizationManager.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/interactors/LearningObjectInteractor.ts
  src/interactors/interactors.ts
  src/interfaces/DataStore.ts
  src/middleware/authenticated-access.ts
  src/middleware/functions.ts
  src/middleware/process-token.ts
  src/tests/mock-drivers/MockDataStore.ts
  src/tests/mocks.ts
  src/types/index.ts
  src/types/learning-object-document.ts
Labels: review

#224 Fix bad function call
  package-lock.json
  package.json
  src/SingleFileDownload/SingleFileDownloadInteractor.ts
Labels: review

#229 Implement route to load user's profile
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressRouteDriver.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/interactors/LearningObjectInteractor.ts
  src/interfaces/DataStore.ts
  test_environment/globalConfig.json
Labels: review

#216 Add route for children
  package-lock.json
  package.json
  src/LearningObjects/LearningObjectInteractor.spec.ts
  src/LearningObjects/LearningObjectInteractor.ts
  src/LearningObjects/LearningObjectRouteHandler.ts
Labels: review

#233 :ambulance: Fix broken search for reviewers/curators
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#234 Remove invalid characters in LO name for PDF filename
  package-lock.json
  package.json
  src/LearningObjects/PDFKitDriver.ts
Labels: review

#221 Hotfix/review stats
  package-lock.json
  package.json
  src/LearningObjectStats/LearningObjectStatStore.ts
  src/LearningObjectStats/LearningObjectStatsInteractor.ts
  src/LearningObjects/LearningObjectInteractor.spec.ts
  src/LearningObjects/LearningObjectInteractor.ts
  src/LearningObjects/LearningObjectRouteHandler.ts
  src/types/user-token.ts
Labels: review

#239 Feature/collection stats
  package-lock.json
  package.json
  src/LearningObjectStats/LearningObjectStatStore.ts
  src/LearningObjectStats/LearningObjectStatsInteractor.ts
Labels: review

#240 Fix reviewers/curators receiving objects in review when requesting released
  package-lock.json
  package.json
  src/interactors/LearningObjectInteractor.ts
Labels: review

#208 Service returns 500 when a user is not found
  package-lock.json
  package.json
  src/Changelogs/ChangelogDatastore.ts
  src/Changelogs/ChangelogInteractor.ts
  src/Changelogs/ChangelogRouteDriver.ts
  src/LearningObjectSubmission/SubmissionInteractor.ts
  src/LearningObjectSubmission/SubmissionRouteDriver.ts
  src/LearningObjects/LearningObjectInteractor.ts
  src/LearningObjects/LearningObjectRouteHandler.ts
  src/SingleFileDownload/RouteHandler.ts
  src/drivers/MongoDriver.spec.ts
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/drivers/express/ExpressRouteDriver.ts
  src/errors.ts
  src/interactors/LearningObjectInteractor.ts
Labels: bug, review

#244 Fix fetch for released learning objects
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/interactors/LearningObjectInteractor.ts
Labels: review

#242 Add functionality to manage released and working files
  package-lock.json
  package.json
  src/FileManager/S3Driver.ts
  src/SingleFileDownload/SingleFileDownloadInteractor.ts
  src/interfaces/FileManager.ts
  src/tests/mock-drivers/MockS3Driver.ts
Labels: review

#246 Fix Learning Object updates failing
  package-lock.json
  package.json
  src/LearningObjects/LearningObjectRouteHandler.ts
Labels: review

#247 :bug: Fix call to copy object to collection
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#248 Fix aggregation sort not being applied
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#252 Fix cyclic dependency caused by not awaiting promises
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#257 :bug: Fix collection pointer in searchReleasedObjects
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
Labels: review

#256 Fix Learning Objects not being found if the released copy's name was different from working copy's name
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/interactors/LearningObjectInteractor.ts
  src/interfaces/DataStore.ts
  src/tests/mock-drivers/MockDataStore.ts
Labels: review

#258 Re-add route to fetch Learning Object's Id & Add authorization logic
  package-lock.json
  package.json
  src/drivers/express/ExpressAuthRouteDriver.ts
  src/interactors/AuthorizationManager.ts
  src/interactors/LearningObject.interactor.spec.ts
  src/interactors/LearningObjectInteractor.ts
  src/types/index.ts
  src/types/service-token.ts
Labels: review

#261 Fix parents route fetching unreleased parents
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/drivers/express/ExpressRouteDriver.ts
  src/interactors/LearningObjectInteractor.ts
  src/interfaces/DataStore.ts
  src/tests/mock-drivers/MockDataStore.ts
  test_environment/globalConfig.json
Labels: review
